// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airqualityservice.proto

package ds.airqualityservice;

public final class AirQualityServiceImpl {
  private AirQualityServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airquality_GetLatestReadingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airquality_GetLatestReadingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airquality_GetLatestReadingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airquality_GetLatestReadingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airquality_GetHistoricalDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airquality_GetHistoricalDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airquality_GetHistoricalDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airquality_GetHistoricalDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027airqualityservice.proto\022\nairquality\"0\n" +
      "\027GetLatestReadingRequest\022\025\n\rlatestreadin" +
      "g\030\001 \001(\t\")\n\030GetLatestReadingResponse\022\r\n\005p" +
      "m2_5\030\001 \001(\005\"C\n\030GetHistoricalDataRequest\022\025" +
      "\n\rlatestreading\030\001 \001(\t\022\020\n\010num_days\030\002 \001(\005\"" +
      "=\n\031GetHistoricalDataResponse\022\021\n\tsensor_i" +
      "d\030\001 \001(\t\022\r\n\005pm2_5\030\002 \001(\0022\332\001\n\021AirQualitySer" +
      "vice\022_\n\020GetLatestReading\022#.airquality.Ge" +
      "tLatestReadingRequest\032$.airquality.GetLa" +
      "testReadingResponse\"\000\022d\n\021GetHistoricalDa" +
      "ta\022$.airquality.GetHistoricalDataRequest" +
      "\032%.airquality.GetHistoricalDataResponse\"" +
      "\0000\001B/\n\024ds.airqualityserviceB\025AirQualityS" +
      "erviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_airquality_GetLatestReadingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_airquality_GetLatestReadingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airquality_GetLatestReadingRequest_descriptor,
        new java.lang.String[] { "Latestreading", });
    internal_static_airquality_GetLatestReadingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_airquality_GetLatestReadingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airquality_GetLatestReadingResponse_descriptor,
        new java.lang.String[] { "Pm25", });
    internal_static_airquality_GetHistoricalDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_airquality_GetHistoricalDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airquality_GetHistoricalDataRequest_descriptor,
        new java.lang.String[] { "Latestreading", "NumDays", });
    internal_static_airquality_GetHistoricalDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_airquality_GetHistoricalDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airquality_GetHistoricalDataResponse_descriptor,
        new java.lang.String[] { "SensorId", "Pm25", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
