// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airqualityservice.proto

package ds.airqualityservice;

/**
 * Protobuf type {@code airquality.Alert}
 */
public  final class Alert extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:airquality.Alert)
    AlertOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Alert.newBuilder() to construct.
  private Alert(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Alert() {
    sensorId_ = "";
    pm25_ = 0F;
    pm10_ = 0F;
    ozone_ = 0F;
    nitrogenDioxide_ = 0F;
    sulfurDioxide_ = 0F;
    timestamp_ = 0L;
    message_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Alert(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sensorId_ = s;
            break;
          }
          case 21: {

            pm25_ = input.readFloat();
            break;
          }
          case 29: {

            pm10_ = input.readFloat();
            break;
          }
          case 37: {

            ozone_ = input.readFloat();
            break;
          }
          case 45: {

            nitrogenDioxide_ = input.readFloat();
            break;
          }
          case 53: {

            sulfurDioxide_ = input.readFloat();
            break;
          }
          case 56: {

            timestamp_ = input.readInt64();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.airqualityservice.AirQualityServiceImpl.internal_static_airquality_Alert_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.airqualityservice.AirQualityServiceImpl.internal_static_airquality_Alert_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.airqualityservice.Alert.class, ds.airqualityservice.Alert.Builder.class);
  }

  public static final int SENSOR_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object sensorId_;
  /**
   * <code>string sensor_id = 1;</code>
   */
  public java.lang.String getSensorId() {
    java.lang.Object ref = sensorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sensorId_ = s;
      return s;
    }
  }
  /**
   * <code>string sensor_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSensorIdBytes() {
    java.lang.Object ref = sensorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sensorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PM2_5_FIELD_NUMBER = 2;
  private float pm25_;
  /**
   * <code>float pm2_5 = 2;</code>
   */
  public float getPm25() {
    return pm25_;
  }

  public static final int PM10_FIELD_NUMBER = 3;
  private float pm10_;
  /**
   * <code>float pm10 = 3;</code>
   */
  public float getPm10() {
    return pm10_;
  }

  public static final int OZONE_FIELD_NUMBER = 4;
  private float ozone_;
  /**
   * <code>float ozone = 4;</code>
   */
  public float getOzone() {
    return ozone_;
  }

  public static final int NITROGEN_DIOXIDE_FIELD_NUMBER = 5;
  private float nitrogenDioxide_;
  /**
   * <code>float nitrogen_dioxide = 5;</code>
   */
  public float getNitrogenDioxide() {
    return nitrogenDioxide_;
  }

  public static final int SULFUR_DIOXIDE_FIELD_NUMBER = 6;
  private float sulfurDioxide_;
  /**
   * <code>float sulfur_dioxide = 6;</code>
   */
  public float getSulfurDioxide() {
    return sulfurDioxide_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 7;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 8;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 8;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 8;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSensorIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sensorId_);
    }
    if (pm25_ != 0F) {
      output.writeFloat(2, pm25_);
    }
    if (pm10_ != 0F) {
      output.writeFloat(3, pm10_);
    }
    if (ozone_ != 0F) {
      output.writeFloat(4, ozone_);
    }
    if (nitrogenDioxide_ != 0F) {
      output.writeFloat(5, nitrogenDioxide_);
    }
    if (sulfurDioxide_ != 0F) {
      output.writeFloat(6, sulfurDioxide_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, message_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSensorIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sensorId_);
    }
    if (pm25_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, pm25_);
    }
    if (pm10_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, pm10_);
    }
    if (ozone_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, ozone_);
    }
    if (nitrogenDioxide_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, nitrogenDioxide_);
    }
    if (sulfurDioxide_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, sulfurDioxide_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, message_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.airqualityservice.Alert)) {
      return super.equals(obj);
    }
    ds.airqualityservice.Alert other = (ds.airqualityservice.Alert) obj;

    boolean result = true;
    result = result && getSensorId()
        .equals(other.getSensorId());
    result = result && (
        java.lang.Float.floatToIntBits(getPm25())
        == java.lang.Float.floatToIntBits(
            other.getPm25()));
    result = result && (
        java.lang.Float.floatToIntBits(getPm10())
        == java.lang.Float.floatToIntBits(
            other.getPm10()));
    result = result && (
        java.lang.Float.floatToIntBits(getOzone())
        == java.lang.Float.floatToIntBits(
            other.getOzone()));
    result = result && (
        java.lang.Float.floatToIntBits(getNitrogenDioxide())
        == java.lang.Float.floatToIntBits(
            other.getNitrogenDioxide()));
    result = result && (
        java.lang.Float.floatToIntBits(getSulfurDioxide())
        == java.lang.Float.floatToIntBits(
            other.getSulfurDioxide()));
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENSOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSensorId().hashCode();
    hash = (37 * hash) + PM2_5_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPm25());
    hash = (37 * hash) + PM10_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPm10());
    hash = (37 * hash) + OZONE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getOzone());
    hash = (37 * hash) + NITROGEN_DIOXIDE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getNitrogenDioxide());
    hash = (37 * hash) + SULFUR_DIOXIDE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSulfurDioxide());
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.airqualityservice.Alert parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.airqualityservice.Alert parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.airqualityservice.Alert parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.airqualityservice.Alert parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.airqualityservice.Alert parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.airqualityservice.Alert parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.airqualityservice.Alert parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.airqualityservice.Alert parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.airqualityservice.Alert parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.airqualityservice.Alert parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.airqualityservice.Alert parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.airqualityservice.Alert parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.airqualityservice.Alert prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code airquality.Alert}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:airquality.Alert)
      ds.airqualityservice.AlertOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.airqualityservice.AirQualityServiceImpl.internal_static_airquality_Alert_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.airqualityservice.AirQualityServiceImpl.internal_static_airquality_Alert_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.airqualityservice.Alert.class, ds.airqualityservice.Alert.Builder.class);
    }

    // Construct using ds.airqualityservice.Alert.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sensorId_ = "";

      pm25_ = 0F;

      pm10_ = 0F;

      ozone_ = 0F;

      nitrogenDioxide_ = 0F;

      sulfurDioxide_ = 0F;

      timestamp_ = 0L;

      message_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.airqualityservice.AirQualityServiceImpl.internal_static_airquality_Alert_descriptor;
    }

    @java.lang.Override
    public ds.airqualityservice.Alert getDefaultInstanceForType() {
      return ds.airqualityservice.Alert.getDefaultInstance();
    }

    @java.lang.Override
    public ds.airqualityservice.Alert build() {
      ds.airqualityservice.Alert result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.airqualityservice.Alert buildPartial() {
      ds.airqualityservice.Alert result = new ds.airqualityservice.Alert(this);
      result.sensorId_ = sensorId_;
      result.pm25_ = pm25_;
      result.pm10_ = pm10_;
      result.ozone_ = ozone_;
      result.nitrogenDioxide_ = nitrogenDioxide_;
      result.sulfurDioxide_ = sulfurDioxide_;
      result.timestamp_ = timestamp_;
      result.message_ = message_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.airqualityservice.Alert) {
        return mergeFrom((ds.airqualityservice.Alert)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.airqualityservice.Alert other) {
      if (other == ds.airqualityservice.Alert.getDefaultInstance()) return this;
      if (!other.getSensorId().isEmpty()) {
        sensorId_ = other.sensorId_;
        onChanged();
      }
      if (other.getPm25() != 0F) {
        setPm25(other.getPm25());
      }
      if (other.getPm10() != 0F) {
        setPm10(other.getPm10());
      }
      if (other.getOzone() != 0F) {
        setOzone(other.getOzone());
      }
      if (other.getNitrogenDioxide() != 0F) {
        setNitrogenDioxide(other.getNitrogenDioxide());
      }
      if (other.getSulfurDioxide() != 0F) {
        setSulfurDioxide(other.getSulfurDioxide());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.airqualityservice.Alert parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.airqualityservice.Alert) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object sensorId_ = "";
    /**
     * <code>string sensor_id = 1;</code>
     */
    public java.lang.String getSensorId() {
      java.lang.Object ref = sensorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sensorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sensor_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSensorIdBytes() {
      java.lang.Object ref = sensorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sensor_id = 1;</code>
     */
    public Builder setSensorId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sensorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sensor_id = 1;</code>
     */
    public Builder clearSensorId() {
      
      sensorId_ = getDefaultInstance().getSensorId();
      onChanged();
      return this;
    }
    /**
     * <code>string sensor_id = 1;</code>
     */
    public Builder setSensorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sensorId_ = value;
      onChanged();
      return this;
    }

    private float pm25_ ;
    /**
     * <code>float pm2_5 = 2;</code>
     */
    public float getPm25() {
      return pm25_;
    }
    /**
     * <code>float pm2_5 = 2;</code>
     */
    public Builder setPm25(float value) {
      
      pm25_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float pm2_5 = 2;</code>
     */
    public Builder clearPm25() {
      
      pm25_ = 0F;
      onChanged();
      return this;
    }

    private float pm10_ ;
    /**
     * <code>float pm10 = 3;</code>
     */
    public float getPm10() {
      return pm10_;
    }
    /**
     * <code>float pm10 = 3;</code>
     */
    public Builder setPm10(float value) {
      
      pm10_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float pm10 = 3;</code>
     */
    public Builder clearPm10() {
      
      pm10_ = 0F;
      onChanged();
      return this;
    }

    private float ozone_ ;
    /**
     * <code>float ozone = 4;</code>
     */
    public float getOzone() {
      return ozone_;
    }
    /**
     * <code>float ozone = 4;</code>
     */
    public Builder setOzone(float value) {
      
      ozone_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float ozone = 4;</code>
     */
    public Builder clearOzone() {
      
      ozone_ = 0F;
      onChanged();
      return this;
    }

    private float nitrogenDioxide_ ;
    /**
     * <code>float nitrogen_dioxide = 5;</code>
     */
    public float getNitrogenDioxide() {
      return nitrogenDioxide_;
    }
    /**
     * <code>float nitrogen_dioxide = 5;</code>
     */
    public Builder setNitrogenDioxide(float value) {
      
      nitrogenDioxide_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float nitrogen_dioxide = 5;</code>
     */
    public Builder clearNitrogenDioxide() {
      
      nitrogenDioxide_ = 0F;
      onChanged();
      return this;
    }

    private float sulfurDioxide_ ;
    /**
     * <code>float sulfur_dioxide = 6;</code>
     */
    public float getSulfurDioxide() {
      return sulfurDioxide_;
    }
    /**
     * <code>float sulfur_dioxide = 6;</code>
     */
    public Builder setSulfurDioxide(float value) {
      
      sulfurDioxide_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float sulfur_dioxide = 6;</code>
     */
    public Builder clearSulfurDioxide() {
      
      sulfurDioxide_ = 0F;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 7;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 7;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 7;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 8;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 8;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 8;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 8;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:airquality.Alert)
  }

  // @@protoc_insertion_point(class_scope:airquality.Alert)
  private static final ds.airqualityservice.Alert DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.airqualityservice.Alert();
  }

  public static ds.airqualityservice.Alert getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Alert>
      PARSER = new com.google.protobuf.AbstractParser<Alert>() {
    @java.lang.Override
    public Alert parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Alert(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Alert> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Alert> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.airqualityservice.Alert getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

