// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airqualityservice.proto

package ds.airqualityservice;

public interface GetHistoricalDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.GetHistoricalDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string latestreading = 1;</code>
   */
  java.lang.String getLatestreading();
  /**
   * <code>string latestreading = 1;</code>
   */
  com.google.protobuf.ByteString
      getLatestreadingBytes();

  /**
   * <code>int32 num_days = 2;</code>
   */
  int getNumDays();
}
