// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airqualityservice.proto

package ds.airqualityservice;

public interface GetHistoricalDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.GetHistoricalDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor_id = 1;</code>
   */
  java.lang.String getSensorId();
  /**
   * <code>string sensor_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSensorIdBytes();

  /**
   * <code>float pm2_5 = 2;</code>
   */
  float getPm25();
}
