// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airqualityservice.proto

package ds.airqualityservice;

/**
 * Protobuf type {@code airquality.GetLatestReadingResponse}
 */
public  final class GetLatestReadingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:airquality.GetLatestReadingResponse)
    GetLatestReadingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetLatestReadingResponse.newBuilder() to construct.
  private GetLatestReadingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetLatestReadingResponse() {
    pm25_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetLatestReadingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            pm25_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.airqualityservice.AirQualityServiceImpl.internal_static_airquality_GetLatestReadingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.airqualityservice.AirQualityServiceImpl.internal_static_airquality_GetLatestReadingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.airqualityservice.GetLatestReadingResponse.class, ds.airqualityservice.GetLatestReadingResponse.Builder.class);
  }

  public static final int PM2_5_FIELD_NUMBER = 1;
  private int pm25_;
  /**
   * <code>int32 pm2_5 = 1;</code>
   */
  public int getPm25() {
    return pm25_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pm25_ != 0) {
      output.writeInt32(1, pm25_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pm25_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, pm25_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.airqualityservice.GetLatestReadingResponse)) {
      return super.equals(obj);
    }
    ds.airqualityservice.GetLatestReadingResponse other = (ds.airqualityservice.GetLatestReadingResponse) obj;

    boolean result = true;
    result = result && (getPm25()
        == other.getPm25());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PM2_5_FIELD_NUMBER;
    hash = (53 * hash) + getPm25();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.airqualityservice.GetLatestReadingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.airqualityservice.GetLatestReadingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.airqualityservice.GetLatestReadingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.airqualityservice.GetLatestReadingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.airqualityservice.GetLatestReadingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.airqualityservice.GetLatestReadingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.airqualityservice.GetLatestReadingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.airqualityservice.GetLatestReadingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.airqualityservice.GetLatestReadingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.airqualityservice.GetLatestReadingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.airqualityservice.GetLatestReadingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.airqualityservice.GetLatestReadingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.airqualityservice.GetLatestReadingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code airquality.GetLatestReadingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:airquality.GetLatestReadingResponse)
      ds.airqualityservice.GetLatestReadingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.airqualityservice.AirQualityServiceImpl.internal_static_airquality_GetLatestReadingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.airqualityservice.AirQualityServiceImpl.internal_static_airquality_GetLatestReadingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.airqualityservice.GetLatestReadingResponse.class, ds.airqualityservice.GetLatestReadingResponse.Builder.class);
    }

    // Construct using ds.airqualityservice.GetLatestReadingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      pm25_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.airqualityservice.AirQualityServiceImpl.internal_static_airquality_GetLatestReadingResponse_descriptor;
    }

    @java.lang.Override
    public ds.airqualityservice.GetLatestReadingResponse getDefaultInstanceForType() {
      return ds.airqualityservice.GetLatestReadingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.airqualityservice.GetLatestReadingResponse build() {
      ds.airqualityservice.GetLatestReadingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.airqualityservice.GetLatestReadingResponse buildPartial() {
      ds.airqualityservice.GetLatestReadingResponse result = new ds.airqualityservice.GetLatestReadingResponse(this);
      result.pm25_ = pm25_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.airqualityservice.GetLatestReadingResponse) {
        return mergeFrom((ds.airqualityservice.GetLatestReadingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.airqualityservice.GetLatestReadingResponse other) {
      if (other == ds.airqualityservice.GetLatestReadingResponse.getDefaultInstance()) return this;
      if (other.getPm25() != 0) {
        setPm25(other.getPm25());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.airqualityservice.GetLatestReadingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.airqualityservice.GetLatestReadingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int pm25_ ;
    /**
     * <code>int32 pm2_5 = 1;</code>
     */
    public int getPm25() {
      return pm25_;
    }
    /**
     * <code>int32 pm2_5 = 1;</code>
     */
    public Builder setPm25(int value) {
      
      pm25_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pm2_5 = 1;</code>
     */
    public Builder clearPm25() {
      
      pm25_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:airquality.GetLatestReadingResponse)
  }

  // @@protoc_insertion_point(class_scope:airquality.GetLatestReadingResponse)
  private static final ds.airqualityservice.GetLatestReadingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.airqualityservice.GetLatestReadingResponse();
  }

  public static ds.airqualityservice.GetLatestReadingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetLatestReadingResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetLatestReadingResponse>() {
    @java.lang.Override
    public GetLatestReadingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetLatestReadingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetLatestReadingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetLatestReadingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.airqualityservice.GetLatestReadingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

