// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airqualityservice.proto

package ds.airqualityservice;

public interface GetLatestReadingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.GetLatestReadingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensor_id = 1;</code>
   */
  java.lang.String getSensorId();
  /**
   * <code>string sensor_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSensorIdBytes();
}
