// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airqualityservice.proto

package ds.airqualityservice;

public interface GetLatestReadingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.GetLatestReadingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.airquality.AirQualityReading reading = 1;</code>
   */
  boolean hasReading();
  /**
   * <code>.airquality.AirQualityReading reading = 1;</code>
   */
  ds.airqualityservice.AirQualityReading getReading();
  /**
   * <code>.airquality.AirQualityReading reading = 1;</code>
   */
  ds.airqualityservice.AirQualityReadingOrBuilder getReadingOrBuilder();
}
