// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airqualityservice.proto

package ds.airqualityservice;

public interface GetLatestReadingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airquality.GetLatestReadingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pm2_5 = 1;</code>
   */
  int getPm25();
}
